import { Roboto } from "next/font/google";
import Navbar from "../component/Navbar";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight:['400', '500', '900'],subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Next Hero",
    template: "%s | Next Hero"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        <div>
        {children}
        </div>
        <footer>This Is Footer</footer>
      </body>
    </html>
  );
}
